// /*
// Auto-generated by: https://github.com/pmndrs/gltfjsx
// Command: npx gltfjsx@6.2.15 public/maplethief_scene/dancethief.glb 
// */

// import React, { useRef, useEffect } from 'react'
// import { useGLTF, useAnimations } from '@react-three/drei'
// import { useCharacterAnimations } from './useCharacterAnimations'
 
// const DanceThief = (props) => {
//   const group = useRef()
//   const { nodes, materials, animations } = useGLTF('./maplethief_scene/dancethief.glb')
//   const { setAnimations, animationIndex } = useCharacterAnimations();
//   const { actions, names } = useAnimations(animations, group);
  
//   const maplethief = useGLTF("./maplethief_scene/dancethiefs.glb"); 

//   useEffect(() => {
//     setAnimations(names);
//   }, [names]);

//   useEffect(() => {
//     actions[names[animationIndex]].reset().fadeIn(0.5).play();
//     return () => {
//       actions[names[animationIndex]].fadeOut(0.5);
//     };
//   }, [animationIndex]);

  

//   return (
//     <group ref={group} {...props} dispose={null}>
//       <group name="Scene">
//         <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={0.302}>
//           <group name="dfdd300ba5324b1bb4bdea28842a9d50fbx" rotation={[Math.PI / 2, 0, 0]}>
//             <group name="RootNode1">
//               <group name="bottom" position={[0, -100.1, 0]} rotation={[Math.PI / 2, Math.PI / 2, 0]}>
//                 <group name="Object_4" />
//               </group>
//               <group name="left" position={[-100.125, 1.608, 0.221]}>
//                 <group name="Object_6" />
//               </group>
//               <group name="Thief_Original">
//                 <group name="Belt" />
//                 <group name="Face1">
//                   <group name="Eyepatch" />
//                   <group name="Helmet" position={[0, -0.018, -0.321]} rotation={[0.091, 0, 0]}>
//                     <group name="Glass_Base" position={[0, 0.029, -0.13]} rotation={[0.027, 0, 0]}>
//                       <group name="Glass_L" />
//                       <group name="Glass_R" />
//                       <group name="Glass_Robe" />
//                     </group>
//                   </group>
//                 </group>
//                 <group name="Hair" />
//                 <group name="polySurface50" />
//                 <group name="polySurface51" />
//                 <group name="polySurface52" />
//                 <group name="polySurface53" />
//                 <group name="polySurface54" />
//                 <group name="polySurface55" />
//                 <group name="polySurface56" />
//                 <group name="polySurface59" />
//                 <group name="polySurface60" />
//                 <group name="polySurface61" />
//                 <group name="polySurface62" />
//                 <group name="polySurface63" />
//                 <group name="Shirt2" />
//                 <group name="Weapon">
//                   <group name="polySurface1" />
//                 </group>
//                 <group name="WeaponBelt" />
//               </group>
//             </group>
//           </group>
//         </group>
//         <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
//           <primitive object={nodes.mixamorigHips} />
//           <skinnedMesh name="Belt_Beltetc_0" geometry={nodes.Belt_Beltetc_0.geometry} material={materials['Beltetc.001']} skeleton={nodes.Belt_Beltetc_0.skeleton} />
//           <skinnedMesh name="Eyepatch_Face_0" geometry={nodes.Eyepatch_Face_0.geometry} material={materials['Face.001']} skeleton={nodes.Eyepatch_Face_0.skeleton} />
//           <skinnedMesh name="Face1_Face_0" geometry={nodes.Face1_Face_0.geometry} material={materials['Face.001']} skeleton={nodes.Face1_Face_0.skeleton} />
//           <skinnedMesh name="Glass_Base_Glass1_0" geometry={nodes.Glass_Base_Glass1_0.geometry} material={materials['Glass1.001']} skeleton={nodes.Glass_Base_Glass1_0.skeleton} />
//           <skinnedMesh name="Glass_L_Glass1_0" geometry={nodes.Glass_L_Glass1_0.geometry} material={materials['Glass1.001']} skeleton={nodes.Glass_L_Glass1_0.skeleton} />
//           <skinnedMesh name="Glass_R_Glass1_0" geometry={nodes.Glass_R_Glass1_0.geometry} material={materials['Glass1.001']} skeleton={nodes.Glass_R_Glass1_0.skeleton} />
//           <skinnedMesh name="Glass_Robe_Glass1_0" geometry={nodes.Glass_Robe_Glass1_0.geometry} material={materials['Glass1.001']} skeleton={nodes.Glass_Robe_Glass1_0.skeleton} />
//           <skinnedMesh name="Hair_lambert5_0" geometry={nodes.Hair_lambert5_0.geometry} material={materials['lambert5.001']} skeleton={nodes.Hair_lambert5_0.skeleton} />
//           <skinnedMesh name="Helmet_Mat_Helmet_0" geometry={nodes.Helmet_Mat_Helmet_0.geometry} material={materials['Mat_Helmet.001']} skeleton={nodes.Helmet_Mat_Helmet_0.skeleton} />
//           <skinnedMesh name="polySurface1_lambert9_0" geometry={nodes.polySurface1_lambert9_0.geometry} material={materials['lambert9.001']} skeleton={nodes.polySurface1_lambert9_0.skeleton} />
//           <skinnedMesh name="polySurface50_Beltetc_0" geometry={nodes.polySurface50_Beltetc_0.geometry} material={materials['Beltetc.001']} skeleton={nodes.polySurface50_Beltetc_0.skeleton} />
//           <skinnedMesh name="polySurface51_Beltetc_0" geometry={nodes.polySurface51_Beltetc_0.geometry} material={materials['Beltetc.001']} skeleton={nodes.polySurface51_Beltetc_0.skeleton} />
//           <skinnedMesh name="polySurface52_Beltetc_0" geometry={nodes.polySurface52_Beltetc_0.geometry} material={materials['Beltetc.001']} skeleton={nodes.polySurface52_Beltetc_0.skeleton} />
//           <skinnedMesh name="polySurface53_Beltetc_0" geometry={nodes.polySurface53_Beltetc_0.geometry} material={materials['Beltetc.001']} skeleton={nodes.polySurface53_Beltetc_0.skeleton} />
//           <skinnedMesh name="polySurface54_Beltetc_0" geometry={nodes.polySurface54_Beltetc_0.geometry} material={materials['Beltetc.001']} skeleton={nodes.polySurface54_Beltetc_0.skeleton} />
//           <skinnedMesh name="polySurface55_Beltetc_0" geometry={nodes.polySurface55_Beltetc_0.geometry} material={materials['Beltetc.001']} skeleton={nodes.polySurface55_Beltetc_0.skeleton} />
//           <skinnedMesh name="polySurface56_Beltetc_0" geometry={nodes.polySurface56_Beltetc_0.geometry} material={materials['Beltetc.001']} skeleton={nodes.polySurface56_Beltetc_0.skeleton} />
//           <skinnedMesh name="polySurface59_Body_0" geometry={nodes.polySurface59_Body_0.geometry} material={materials['Body.001']} skeleton={nodes.polySurface59_Body_0.skeleton} />
//           <skinnedMesh name="polySurface60_Body_0" geometry={nodes.polySurface60_Body_0.geometry} material={materials['Body.001']} skeleton={nodes.polySurface60_Body_0.skeleton} />
//           <skinnedMesh name="polySurface61_Body_0" geometry={nodes.polySurface61_Body_0.geometry} material={materials['Body.001']} skeleton={nodes.polySurface61_Body_0.skeleton} />
//           <skinnedMesh name="polySurface62_Body_0" geometry={nodes.polySurface62_Body_0.geometry} material={materials['Body.001']} skeleton={nodes.polySurface62_Body_0.skeleton} />
//           <skinnedMesh name="polySurface63_Body_0" geometry={nodes.polySurface63_Body_0.geometry} material={materials['Body.001']} skeleton={nodes.polySurface63_Body_0.skeleton} />
//           <skinnedMesh name="Shirt2_Shirt_0" geometry={nodes.Shirt2_Shirt_0.geometry} material={materials['Shirt.001']} skeleton={nodes.Shirt2_Shirt_0.skeleton} />
//           <skinnedMesh name="Weapon_Beltetc_0" geometry={nodes.Weapon_Beltetc_0.geometry} material={materials['Beltetc.001']} skeleton={nodes.Weapon_Beltetc_0.skeleton} />
//           <skinnedMesh name="WeaponBelt_Beltetc_0" geometry={nodes.WeaponBelt_Beltetc_0.geometry} material={materials['Beltetc.001']} skeleton={nodes.WeaponBelt_Beltetc_0.skeleton} />
//         </group>
//       </group>
//     </group>
//   )
// }
// export default DanceThief;
// useGLTF.preload('/dancethief.glb')







import React, { useRef, useEffect } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';
import { useCharacterAnimations } from './useCharacterAnimations';
import { OrbitControls, Preload } from "@react-three/drei";

const DanceThief = () => {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF('./maplethief_scene/dancethiefs.glb');
  const { setAnimations, animationIndex } = useCharacterAnimations();
  const { actions, names } = useAnimations(animations, group);

  useEffect(() => {
    setAnimations(names);
  }, [names]);

  useEffect(() => {

    console.log("Names:", names);
    actions[names[animationIndex]].reset().fadeIn(0.5).play();
    return () => {
      actions[names[animationIndex]].fadeOut(0.5);
    };
  }, [actions, animationIndex]);

  return (
    <group ref={group} dispose={null} scale={[3, 3, 3]}>
      <primitive object={nodes.Scene} />
    </group>
  );
};

export default DanceThief;





